on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        if: ${{ github.event.pull_request.head.repo.owner.login != 'pymor' }}
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `This is a test! ${{github.event.pull_request.head.repo.owner.login}}`
            })

  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event.pull_request.head.repo.owner.login != 'pymor' }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push origin HEAD:_ext_pr_some_id
        if: ${{ github.event.pull_request.head.repo.owner.login != 'pymor' }}
