on:
  pull_request_target:
    types:
      - closed

jobs:
  delete_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
        if: ${{ github.event.pull_request.head.repo.owner.login != 'pymor' }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push origin --delete _ext_pr_some_id
        if: ${{ github.event.pull_request.head.repo.owner.login != 'pymor' }}
